// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXn1cZn-npvLZ0z0Qkhw5bru41_JfwInY',
    appId: '1:572745596193:web:594e8cfe4031d19a6a5260',
    messagingSenderId: '572745596193',
    projectId: 'stroke-e4e27',
    authDomain: 'stroke-e4e27.firebaseapp.com',
    storageBucket: 'stroke-e4e27.firebasestorage.app',
    measurementId: 'G-5THVCY3RGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3WnbxqNCOfl2vgMgZwdkJ-HbZzJZWUCI',
    appId: '1:572745596193:android:d42051a92936cec46a5260',
    messagingSenderId: '572745596193',
    projectId: 'stroke-e4e27',
    storageBucket: 'stroke-e4e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeuGON7irtzDgFngN6eUfgH3g6CEIKeBo',
    appId: '1:572745596193:ios:dff827134f6dad546a5260',
    messagingSenderId: '572745596193',
    projectId: 'stroke-e4e27',
    storageBucket: 'stroke-e4e27.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeuGON7irtzDgFngN6eUfgH3g6CEIKeBo',
    appId: '1:572745596193:ios:dff827134f6dad546a5260',
    messagingSenderId: '572745596193',
    projectId: 'stroke-e4e27',
    storageBucket: 'stroke-e4e27.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXn1cZn-npvLZ0z0Qkhw5bru41_JfwInY',
    appId: '1:572745596193:web:f63a159495be7d9e6a5260',
    messagingSenderId: '572745596193',
    projectId: 'stroke-e4e27',
    authDomain: 'stroke-e4e27.firebaseapp.com',
    storageBucket: 'stroke-e4e27.firebasestorage.app',
    measurementId: 'G-J1EW466F3Z',
  );
}
